/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 iphone.gltf 
Author: Navarion (https://sketchfab.com/Navarion)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/free-iphone15-pro-max-ultra-high-quality-1fb1717d5e204302bfe9969ea77293a4
Title: FREE - IPhone15 Pro Max - Ultra High Quality
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/iphone.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['yfSRCfyMalEYgbO_001-material'].geometry} material={materials['yfSRCfyMalEYgbO.001']} />
          <mesh geometry={nodes['yfSRCfyMalEYgbO_001-material_1'].geometry} material={materials['yfSRCfyMalEYgbO.001']} />
          <mesh geometry={nodes['aNKJdeKOByfZlDS_001-material'].geometry} material={materials['aNKJdeKOByfZlDS.001']} />
          <mesh geometry={nodes['cxAXXzdnHJhRByK_001-material'].geometry} material={materials['cxAXXzdnHJhRByK.001']} />
          <mesh geometry={nodes['aDINyfsuELQulbd_001-material'].geometry} material={materials['aDINyfsuELQulbd.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_2'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['AxufFAzeZPglisV_001-material'].geometry} material={materials['AxufFAzeZPglisV.001']} />
          <mesh geometry={nodes['DkAqxRJaVVfbpgF_001-material'].geometry} material={materials['DkAqxRJaVVfbpgF.001']} />
          <mesh geometry={nodes['yfSRCfyMalEYgbO_001-material_2'].geometry} material={materials['yfSRCfyMalEYgbO.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_9'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['yfSRCfyMalEYgbO_001-material_3'].geometry} material={materials['yfSRCfyMalEYgbO.001']} />
          <mesh geometry={nodes['EWuRzSMoXPhEpsh_001-material_1'].geometry} material={materials['EWuRzSMoXPhEpsh.001']} />
          <mesh geometry={nodes['LDbhHgKqQwnfIdk_001-material_2'].geometry} material={materials['LDbhHgKqQwnfIdk.001']} />
          <mesh geometry={nodes['NOlmOyvNOoXnkpD_001-material'].geometry} material={materials['NOlmOyvNOoXnkpD.001']} />
          <mesh geometry={nodes['LuFFEBDynGcfeVH_001-material'].geometry} material={materials['LuFFEBDynGcfeVH.001']} />
          <mesh geometry={nodes['qYATvTCUqTRIxZo_001-material'].geometry} material={materials['qYATvTCUqTRIxZo.001']} />
          <mesh geometry={nodes['saRNhuLSrFYuedf_001-material_1'].geometry} material={materials['saRNhuLSrFYuedf.001']} />
          <mesh geometry={nodes['xEINmDJHJtyYSZS_001-material_5'].geometry} material={materials['xEINmDJHJtyYSZS.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_10'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['LDbhHgKqQwnfIdk_001-material_3'].geometry} material={materials['LDbhHgKqQwnfIdk.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_11'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_12'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['LuFFEBDynGcfeVH_001-material_1'].geometry} material={materials['LuFFEBDynGcfeVH.001']} />
          <mesh geometry={nodes['LDbhHgKqQwnfIdk_001-material_4'].geometry} material={materials['LDbhHgKqQwnfIdk.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_13'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['LDbhHgKqQwnfIdk_001-material_5'].geometry} material={materials['LDbhHgKqQwnfIdk.001']} />
          <mesh geometry={nodes['saRNhuLSrFYuedf_001-material_2'].geometry} material={materials['saRNhuLSrFYuedf.001']} />
          <mesh geometry={nodes['yfSRCfyMalEYgbO_001-material_4'].geometry} material={materials['yfSRCfyMalEYgbO.001']} />
          <mesh geometry={nodes['NOlmOyvNOoXnkpD_001-material_1'].geometry} material={materials['NOlmOyvNOoXnkpD.001']} />
          <mesh geometry={nodes['qYATvTCUqTRIxZo_001-material_1'].geometry} material={materials['qYATvTCUqTRIxZo.001']} />
          <mesh geometry={nodes['EWuRzSMoXPhEpsh_001-material_2'].geometry} material={materials['EWuRzSMoXPhEpsh.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_14'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['xEINmDJHJtyYSZS_001-material_6'].geometry} material={materials['xEINmDJHJtyYSZS.001']} />
          <mesh geometry={nodes['yfSRCfyMalEYgbO_001-material_5'].geometry} material={materials['yfSRCfyMalEYgbO.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_15'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['PqdtqVEhAPzytes_001-material'].geometry} material={materials['PqdtqVEhAPzytes.001']} />
          <mesh geometry={nodes['PqdtqVEhAPzytes_001-material_1'].geometry} material={materials['PqdtqVEhAPzytes.001']} />
          <mesh geometry={nodes['xwVmDXUVpcqUaxI_001-material'].geometry} material={materials['xwVmDXUVpcqUaxI.001']} />
          <mesh geometry={nodes['GvMXDHTSaTFmkSJ_001-material'].geometry} material={materials['GvMXDHTSaTFmkSJ.001']} />
          <mesh geometry={nodes['AwYbcqVpoWkGbAQ_001-material'].geometry} material={materials['AwYbcqVpoWkGbAQ.001']} />
          <mesh geometry={nodes['AwYbcqVpoWkGbAQ_001-material_1'].geometry} material={materials['AwYbcqVpoWkGbAQ.001']} />
          <mesh geometry={nodes['LDbhHgKqQwnfIdk_001-material_6'].geometry} material={materials['LDbhHgKqQwnfIdk.001']} />
          <mesh geometry={nodes['yfSRCfyMalEYgbO_001-material_6'].geometry} material={materials['yfSRCfyMalEYgbO.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_16'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['yfSRCfyMalEYgbO_001-material_7'].geometry} material={materials['yfSRCfyMalEYgbO.001']} />
          <mesh geometry={nodes['LuFFEBDynGcfeVH_001-material_2'].geometry} material={materials['LuFFEBDynGcfeVH.001']} />
          <mesh geometry={nodes['xEINmDJHJtyYSZS_001-material_7'].geometry} material={materials['xEINmDJHJtyYSZS.001']} />
          <mesh geometry={nodes['qYATvTCUqTRIxZo_001-material_2'].geometry} material={materials['qYATvTCUqTRIxZo.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_17'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['LDbhHgKqQwnfIdk_001-material_7'].geometry} material={materials['LDbhHgKqQwnfIdk.001']} />
          <mesh geometry={nodes['NOlmOyvNOoXnkpD_001-material_2'].geometry} material={materials['NOlmOyvNOoXnkpD.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_18'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['saRNhuLSrFYuedf_001-material_3'].geometry} material={materials['saRNhuLSrFYuedf.001']} />
          <mesh geometry={nodes['LDbhHgKqQwnfIdk_001-material_8'].geometry} material={materials['LDbhHgKqQwnfIdk.001']} />
          <mesh geometry={nodes['NOlmOyvNOoXnkpD_001-material_3'].geometry} material={materials['NOlmOyvNOoXnkpD.001']} />
          <mesh geometry={nodes['EWuRzSMoXPhEpsh_001-material_3'].geometry} material={materials['EWuRzSMoXPhEpsh.001']} />
          <mesh geometry={nodes['NOlmOyvNOoXnkpD_001-material_4'].geometry} material={materials['NOlmOyvNOoXnkpD.001']} />
          <mesh geometry={nodes['DkAqxRJaVVfbpgF_001-material_1'].geometry} material={materials['DkAqxRJaVVfbpgF.001']} />
          <mesh geometry={nodes['ydaDdTqttaoNyqb_001-material'].geometry} material={materials['ydaDdTqttaoNyqb.001']} />
          <mesh geometry={nodes['ZREBupwLYjgDWEr_001-material'].geometry} material={materials['ZREBupwLYjgDWEr.001']} />
          <mesh geometry={nodes['McqOaNTsOxXDHPN_001-material'].geometry} material={materials['McqOaNTsOxXDHPN.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_1'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['vVGvlgWlVeyuRGd_001-material'].geometry} material={materials['vVGvlgWlVeyuRGd.001']} />
          <mesh geometry={nodes['LYzqufVZtJPAOrK_001-material'].geometry} material={materials['LYzqufVZtJPAOrK.001']} />
          <mesh geometry={nodes['pcJKaGFbWeBZXrD_001-material'].geometry} material={materials['pcJKaGFbWeBZXrD.001']} />
          <mesh geometry={nodes['eayVjkFqRlYoCjo_001-material'].geometry} material={materials['eayVjkFqRlYoCjo.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_3'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['RmoEuFpVgpnfYAR_001-material'].geometry} material={materials['RmoEuFpVgpnfYAR.001']} />
          <mesh geometry={nodes['LYzqufVZtJPAOrK_001-material_1'].geometry} material={materials['LYzqufVZtJPAOrK.001']} />
          <mesh geometry={nodes['eVzEOxVmiJRhSFf_001-material_1'].geometry} material={materials['eVzEOxVmiJRhSFf.001']} />
          <mesh geometry={nodes['xKVYQnHEpGkCkNs_001-material'].geometry} material={materials['xKVYQnHEpGkCkNs.001']} />
          <mesh geometry={nodes['LYzqufVZtJPAOrK_001-material_2'].geometry} material={materials['LYzqufVZtJPAOrK.001']} />
          <mesh geometry={nodes['LYzqufVZtJPAOrK_001-material_3'].geometry} material={materials['LYzqufVZtJPAOrK.001']} />
          <mesh geometry={nodes['eVzEOxVmiJRhSFf_001-material'].geometry} material={materials['eVzEOxVmiJRhSFf.001']} />
          <mesh geometry={nodes['NRKgvZEGjdqRXhC_001-material'].geometry} material={materials['NRKgvZEGjdqRXhC.001']} />
          <mesh geometry={nodes['UpJorJMRrcMMGfL_001-material'].geometry} material={materials['UpJorJMRrcMMGfL.001']} />
          <mesh geometry={nodes['xEINmDJHJtyYSZS_001-material'].geometry} material={materials['xEINmDJHJtyYSZS.001']} />
          <mesh geometry={nodes['xEINmDJHJtyYSZS_001-material_1'].geometry} material={materials['xEINmDJHJtyYSZS.001']} />
          <mesh geometry={nodes['UpJorJMRrcMMGfL_001-material_1'].geometry} material={materials['UpJorJMRrcMMGfL.001']} />
          <mesh geometry={nodes['UpJorJMRrcMMGfL_001-material_4'].geometry} material={materials['UpJorJMRrcMMGfL.001']} />
          <mesh geometry={nodes['xEINmDJHJtyYSZS_001-material_8'].geometry} material={materials['xEINmDJHJtyYSZS.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_4'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['UpJorJMRrcMMGfL_001-material_2'].geometry} material={materials['UpJorJMRrcMMGfL.001']} />
          <mesh geometry={nodes['UpJorJMRrcMMGfL_001-material_3'].geometry} material={materials['UpJorJMRrcMMGfL.001']} />
          <mesh geometry={nodes['xEINmDJHJtyYSZS_001-material_2'].geometry} material={materials['xEINmDJHJtyYSZS.001']} />
          <mesh geometry={nodes['jCGtFgFjpibdIdA_001-material'].geometry} material={materials['jCGtFgFjpibdIdA.001']} />
          <mesh geometry={nodes['xEINmDJHJtyYSZS_001-material_3'].geometry} material={materials['xEINmDJHJtyYSZS.001']} />
          <mesh geometry={nodes['jCGtFgFjpibdIdA_001-material_1'].geometry} material={materials['jCGtFgFjpibdIdA.001']} />
          <mesh geometry={nodes['jCGtFgFjpibdIdA_001-material_2'].geometry} material={materials['jCGtFgFjpibdIdA.001']} />
          <mesh geometry={nodes['xKVYQnHEpGkCkNs_001-material_1'].geometry} material={materials['xKVYQnHEpGkCkNs.001']} />
          <mesh geometry={nodes['xEINmDJHJtyYSZS_001-material_4'].geometry} material={materials['xEINmDJHJtyYSZS.001']} />
          <mesh geometry={nodes['awHiRXJGHDDsZAe_001-material'].geometry} material={materials['awHiRXJGHDDsZAe.001']} />
          <mesh geometry={nodes['saRNhuLSrFYuedf_001-material'].geometry} material={materials['saRNhuLSrFYuedf.001']} />
          <mesh geometry={nodes['OGleMDoIcQFdDNP_001-material_2'].geometry} material={materials['OGleMDoIcQFdDNP.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_5'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['OGleMDoIcQFdDNP_001-material_3'].geometry} material={materials['OGleMDoIcQFdDNP.001']} />
          <mesh geometry={nodes['OGleMDoIcQFdDNP_001-material_4'].geometry} material={materials['OGleMDoIcQFdDNP.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_6'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['OGleMDoIcQFdDNP_001-material_5'].geometry} material={materials['OGleMDoIcQFdDNP.001']} />
          <mesh geometry={nodes['OGleMDoIcQFdDNP_001-material_6'].geometry} material={materials['OGleMDoIcQFdDNP.001']} />
          <mesh geometry={nodes['GmWBXngFrYhvbdO_001-material'].geometry} material={materials['GmWBXngFrYhvbdO.001']} />
          <mesh geometry={nodes['iWiAPFztgBDxNan_001-material'].geometry} material={materials['iWiAPFztgBDxNan.001']} />
          <mesh geometry={nodes['iWiAPFztgBDxNan_001-material_1'].geometry} material={materials['iWiAPFztgBDxNan.001']} />
          <mesh geometry={nodes['OGleMDoIcQFdDNP_001-material'].geometry} material={materials['OGleMDoIcQFdDNP.001']} />
          <mesh geometry={nodes['tUIxbALjcklqMLh_001-material'].geometry} material={materials['tUIxbALjcklqMLh.001']} />
          <mesh geometry={nodes['OGleMDoIcQFdDNP_001-material_1'].geometry} material={materials['OGleMDoIcQFdDNP.001']} />
          <mesh geometry={nodes['LDbhHgKqQwnfIdk_001-material'].geometry} material={materials['LDbhHgKqQwnfIdk.001']} />
          <mesh geometry={nodes['LDbhHgKqQwnfIdk_001-material_1'].geometry} material={materials['LDbhHgKqQwnfIdk.001']} />
          <mesh geometry={nodes['EtFgaXCoUdBMdxZ_001-material_7'].geometry} material={materials['EtFgaXCoUdBMdxZ.001']} />
          <mesh geometry={nodes['EWuRzSMoXPhEpsh_001-material'].geometry} material={materials['EWuRzSMoXPhEpsh.001']} />
          <mesh geometry={nodes['MeQJBtEiHnDpYBD_001-material'].geometry} material={materials['MeQJBtEiHnDpYBD.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/iphone.gltf')
